parameters:
#    site_platform.example.class: Yan\Bundle\SitePlatformBundle\Example

services:
#    site_platform.example:
#        class: %site_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
